server:
  port: 5050
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
